### PR TITLE
Fix default HTTP client tests

### LINKED ISSUE #317: Fix skipped default HTTP client tests in browser

### PR DESCRIPTION
**Pull request by kpajdzik**
Fix skipped tests for default HTTP client. New tests don't use express.js testserver but only locally mocked calls using axios-mock-provider for Node.js client and xhr-mock for browser client.

Fixes #317

### CODE REVIEW

File: test/defaultHttpClientTests.ts [hunk 1]
```diff
@@ -21,92 +22,40 @@ function getAbortController(): AbortController {
...
 
-const baseURL = "https://example.com";
+const httpMock = getHttpMock();
 
-describe.skip("defaultHttpClient", function () {
-  it("should send HTTP requests", async function () {
-    const request = new WebResource("https://example.com/", "GET");
-    request.headers.set("Access-Control-Allow-Origin", "https://example.com");
-    const httpClient = new DefaultHttpClient();
+describe.only("defaultHttpClient", function () {
```
Comment (daschult) [inline test/defaultHttpClientTests.ts]: Remove .only().
